<%@ page import="java.util.ArrayList"%>
<%@ page import="books.Book"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%
final ArrayList<Book> bookArr = new ArrayList<Book>();

// Data generated by AI
bookArr.add(new Book("978-0134685991", "Effective Java", "Joshua Bloch", "Addison-Wesley", 10, 45.99));
bookArr.add(new Book("978-0596009205", "Head First Java", "Kathy Sierra", "O'Reilly Media", 15, 39.95));
bookArr.add(new Book("978-1491956250", "Java: The Complete Reference", "Herbert Schildt", "McGraw-Hill", 8, 52.50));
bookArr.add(new Book("978-1617291999", "Java Concurrency in Practice", "Brian Goetz", "Addison-Wesley", 5, 49.99));
bookArr.add(new Book("978-0132350884", "Clean Code", "Robert C. Martin", "Prentice Hall", 12, 41.75));
%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Books ArrayList</title>
<script src="https://cdn.tailwindcss.com"></script>
<style>
table, th, td {
	border: 1px solid black;
}
</style>
</head>
<body>
	<table>
		<thead>
			<tr>
				<th>ISBN</th>
				<th>Title</th>
				<th>Author</th>
				<th>Publisher</th>
				<th>Quantity</th>
				<th>Price</th>
				<th>Total Value</th>
			</tr>
		</thead>
		<tbody>
			<%
			for (Book b : bookArr) {
			%>
			<tr>
				<td class="isbn"><%=b.getISBN()%></td>
				<td><%=b.getTitle()%></td>
				<td><%=b.getAuthor()%></td>
				<td><%=b.getPublisher()%></td>
				<td><%=b.getQuantity()%></td>
				<td class="price">$<%=String.format("%.2f", b.getPrice())%></td>
				<td class="price">$<%=String.format("%.2f", b.getPrice() * b.getQuantity())%></td>
			</tr>
			<%
			}
			%>
		</tbody>
	</table>
</body>
</html>